apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: idurar
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: idurar
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30088

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: idurar
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
